<?php

namespace common\models\tables;

use function PHPSTORM_META\type;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\web\View;

/**
 * This is the model class for table "task".
 *
 * @property int $id
 * @property string $name
 * @property string $date_start
 * @property string $description
 * @property int $responsible_id
 * @property int $initiator_id
 * @property int $project_id
 * @property string $date_end
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property User $user
 * @property Project $project
 * @property array $documents
 */
class Task extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'task';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'date_start', 'date_end'], 'required'],
            [['date_start'], 'safe'],
            [['description'], 'string'],
            [['responsible_id', 'initiator_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['responsible_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['responsible_id' => 'id']],
            [['initiator_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['initiator_id' => 'id']],
            [['project_id'], 'exist', 'skipOnError' => true, 'targetClass' => Project::class, 'targetAttribute' => ['project_id' => 'id']],
            ['date_start', 'compare', 'operator' => '<=', 'type' => 'number', 'compareAttribute' => 'date_end'],
        ];
    }

    public function beforeValidate()
    {
        $this->date_start = $this->date_start ?? strtotime($this->date_start);
        $this->date_end = strtotime($this->date_end);

        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function afterValidate()
    {
        $this->date_start = $this->date_start ?? date('Y-m-d', $this->date_start);
        $this->date_end = date('Y-m-d', $this->date_end);

        parent::afterValidate(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'description' => 'Description',
            'responsible_id' => 'Ответственный пользователь',
            'initiator_id' => 'Постановщик задачи',
            'date_start' => 'Дата начала',
            'date_end' => 'Дата завершения',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'responsible_id']);
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::class,
//                'createdAtAttribute' => 'create_time',
//                'updatedAtAttribute' => 'update_time',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    public static function findCurrentTask()
    {
        return self::find()
            ->with('project')
            ->where(['<', 'date_start', date('Y-m-d H:i:s')])
            ->andWhere(['<', 'date_end', date('Y-m-d H:i:s', strtotime('+1 month'))])
            ->andFilterWhere(['or', ['=', 'responsible_id', Yii::$app->user->id],
                ['=', 'initiator_id', Yii::$app->user->id]])
            ->orderBy(['project_id' => 'asc', 'date_start' => 'asc']);
    }

    public function getProject()
    {
        return $this->hasOne(Project::class, ['id' => 'project_id']);
    }

    public function getDocuments()
    {
        $documentsArray = [];
        $documents = $this->hasMany(File::class, ['task_id' => 'id'])->select('file.path')->all();
        foreach ($documents as $file) {
            $pathArray = explode('/', $file->path);
            $url = implode('/', array_slice($pathArray, 3));
            $filename = $pathArray[count($pathArray) - 1];
            if ($pathArray[count($pathArray) - 2] == 'images') {
                $thumbnail = File::getThumbnail($filename);

                $documentsArray[] = [
                    'title' => $filename,
                    'url' => '/' . $url,
                    'thumbnail' => $thumbnail
                ];
            } else {
                $documentsArray[] = [
                    'title' => $filename,
                    'url' => '/' . $url,
                ];
            }
        }
        return $documentsArray;
    }

    public static function getDeadlineTasks()
    {
        return self::find()
            ->with('user')
            ->andWhere(['=', 'date_end', date('Y-m-d', strtotime('+1 days'))])
            ->all();
    }

    public static function getTaskByUserId()
    {
        return self::find()
            ->andFilterWhere(['or', ['=', 'responsible_id', Yii::$app->user->id],
                ['=', 'initiator_id', Yii::$app->user->id]])
            ->all();
    }

    public function getUsedUsersId()
    {
        return array_unique([
            $this->initiator_id,
            $this->responsible_id
        ]);
    }
}
